sudo: false
language: node_js
node_js:
  - '6.2'
  - '4.4'
before_install: npm install -g babel-cli
install: npm install

addons:
  postgresql: "9.4"

services:
  - postgresql
before_script:
  - psql -c 'create database rain_dev;' -U postgres